[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "{{cookiecutter.pkg_name}}"
author = "me"
home-page = "https://github.com:my-username/{{cookiecutter.github_proj}}"
