name: Test the cookiecutter template
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install cookiecutter pytest
    -  name: Use the template
      run: |
        cookiecutter --no-input .
    # I need to add some tests to check the template does all the things I want it to!
    # - name: Test with pytest
    #   run: |
    #     pytest

